server:
  port: 10030
  max-http-header-size: 10240

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/bookmark?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: root

    url: jdbc:mysql://47.96.41.120:3306/bookmark?serverTimezone=GMT%2B8&characterEncoding=utf-8&allowPublicKeyRetrieval=true #&useSSL=false
    username: root
    password: "123456"

mybatis:
  configuration:
    mapUnderscoreToCamelCase: false # 开启驼峰命名转换法
