server:
  port: 10036

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookmark?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  configuration:
    mapUnderscoreToCamelCase: false # 开启驼峰命名转换法
